export {
  canonicalColor,
  categoryHint,
  colorHex,
  fitOf,
  formatPrice,
  isSizeLabel,
  itemInStock,
  itemMatchesQuery,
  type ExperienceItem,
} from './catalog';
export {
  adviceForItem,
  estimateFromStatedHeight,
  recommendFromChart,
  recommendFromHeight,
  sizeScale,
  type BodyInput,
  type ChartSize,
  type FitFeel,
  type SizeAdvice,
} from './advice';
export {
  assistantReply,
  completeLook,
  parseShopCommand,
  productDescription,
  rankForHistory,
  UI_COPY,
  type ShopCommand,
  type ShopQuery,
} from './stylist';
export {
  buildMannequinSpec,
  clampControl,
  gestureFromJoints,
  nextSize,
  nextView,
  type MannequinSpec,
  type MannequinView,
} from './mannequin';
export {
  CATALOG_CACHE_STORAGE_KEY,
  PLAN_IDS,
  PLAN_LIMITS,
  cacheIsFresh,
  gpuUsageEstimate,
  readPlan,
  roleMayManageCatalog,
  roleMayManageDevices,
  rollupSelections,
  sanitizeCatalogCache,
  usageAllowed,
  whiteLabel,
  type CatalogCacheEnvelope,
  type PlanId,
  type PlanLimits,
  type RetailRollup,
  type RetailSelection,
} from './retail';
