// Generated by the Supabase CLI / MCP from the applied migrations.
// Do not edit by hand. Regenerate after every migration.
//
// This file is excluded from ESLint and Prettier because its formatting is
// owned by the generator.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action: string
          actor_display_id: string | null
          actor_kind: Database["public"]["Enums"]["actor_kind"]
          actor_staff_id: string | null
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          ip_address: unknown
          metadata: Json
          organization_id: string
          user_agent: string | null
        }
        Insert: {
          action: string
          actor_display_id?: string | null
          actor_kind: Database["public"]["Enums"]["actor_kind"]
          actor_staff_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          ip_address?: unknown
          metadata?: Json
          organization_id: string
          user_agent?: string | null
        }
        Update: {
          action?: string
          actor_display_id?: string | null
          actor_kind?: Database["public"]["Enums"]["actor_kind"]
          actor_staff_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          ip_address?: unknown
          metadata?: Json
          organization_id?: string
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_display_id_organization_id_fkey"
            columns: ["actor_display_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "audit_logs_actor_staff_id_organization_id_fkey"
            columns: ["actor_staff_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "staff_users"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "audit_logs_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      consents: {
        Row: {
          created_at: string
          granted: boolean
          granted_at: string
          id: string
          kind: Database["public"]["Enums"]["consent_kind"]
          organization_id: string
          policy_version: string
          revoked_at: string | null
          session_id: string
          shop_id: string
        }
        Insert: {
          created_at?: string
          granted: boolean
          granted_at?: string
          id?: string
          kind: Database["public"]["Enums"]["consent_kind"]
          organization_id: string
          policy_version: string
          revoked_at?: string | null
          session_id: string
          shop_id: string
        }
        Update: {
          created_at?: string
          granted?: boolean
          granted_at?: string
          id?: string
          kind?: Database["public"]["Enums"]["consent_kind"]
          organization_id?: string
          policy_version?: string
          revoked_at?: string | null
          session_id?: string
          shop_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "consents_session_id_organization_id_fkey"
            columns: ["session_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "consents_session_id_shop_id_fkey"
            columns: ["session_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "shop_id"]
          },
        ]
      }
      customer_requests: {
        Row: {
          acknowledged_at: string | null
          acknowledged_by: string | null
          cancelled_at: string | null
          created_at: string
          fulfilled_at: string | null
          garment_id: string
          id: string
          note: string | null
          organization_id: string
          requested_at: string
          session_id: string
          shop_id: string
          size_label: Database["public"]["Enums"]["size_label"]
          status: Database["public"]["Enums"]["customer_request_status"]
          updated_at: string
          variant_id: string
        }
        Insert: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          cancelled_at?: string | null
          created_at?: string
          fulfilled_at?: string | null
          garment_id: string
          id?: string
          note?: string | null
          organization_id: string
          requested_at?: string
          session_id: string
          shop_id: string
          size_label: Database["public"]["Enums"]["size_label"]
          status?: Database["public"]["Enums"]["customer_request_status"]
          updated_at?: string
          variant_id: string
        }
        Update: {
          acknowledged_at?: string | null
          acknowledged_by?: string | null
          cancelled_at?: string | null
          created_at?: string
          fulfilled_at?: string | null
          garment_id?: string
          id?: string
          note?: string | null
          organization_id?: string
          requested_at?: string
          session_id?: string
          shop_id?: string
          size_label?: Database["public"]["Enums"]["size_label"]
          status?: Database["public"]["Enums"]["customer_request_status"]
          updated_at?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "customer_requests_acknowledged_by_organization_id_fkey"
            columns: ["acknowledged_by", "organization_id"]
            isOneToOne: false
            referencedRelation: "staff_users"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "customer_requests_garment_id_organization_id_fkey"
            columns: ["garment_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "garments"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "customer_requests_session_id_organization_id_fkey"
            columns: ["session_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "customer_requests_session_id_shop_id_fkey"
            columns: ["session_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "shop_id"]
          },
          {
            foreignKeyName: "customer_requests_variant_id_garment_id_fkey"
            columns: ["variant_id", "garment_id"]
            isOneToOne: false
            referencedRelation: "garment_variants"
            referencedColumns: ["id", "garment_id"]
          },
        ]
      }
      device_credentials: {
        Row: {
          created_at: string
          display_id: string
          expires_at: string | null
          id: string
          issued_at: string
          label: string | null
          last_used_at: string | null
          organization_id: string
          revoked_at: string | null
          secret_hash: string
          shop_id: string
        }
        Insert: {
          created_at?: string
          display_id: string
          expires_at?: string | null
          id?: string
          issued_at?: string
          label?: string | null
          last_used_at?: string | null
          organization_id: string
          revoked_at?: string | null
          secret_hash: string
          shop_id: string
        }
        Update: {
          created_at?: string
          display_id?: string
          expires_at?: string | null
          id?: string
          issued_at?: string
          label?: string | null
          last_used_at?: string | null
          organization_id?: string
          revoked_at?: string | null
          secret_hash?: string
          shop_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "device_credentials_display_id_organization_id_fkey"
            columns: ["display_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "device_credentials_display_id_shop_id_fkey"
            columns: ["display_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "shop_id"]
          },
        ]
      }
      device_heartbeats: {
        Row: {
          app_version: string | null
          camera_ok: boolean | null
          created_at: string
          display_id: string
          id: string
          metrics: Json
          observed_at: string
          organization_id: string
          processing_fps: number | null
          render_fps: number | null
          shop_id: string
        }
        Insert: {
          app_version?: string | null
          camera_ok?: boolean | null
          created_at?: string
          display_id: string
          id?: string
          metrics?: Json
          observed_at?: string
          organization_id: string
          processing_fps?: number | null
          render_fps?: number | null
          shop_id: string
        }
        Update: {
          app_version?: string | null
          camera_ok?: boolean | null
          created_at?: string
          display_id?: string
          id?: string
          metrics?: Json
          observed_at?: string
          organization_id?: string
          processing_fps?: number | null
          render_fps?: number | null
          shop_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "device_heartbeats_display_id_organization_id_fkey"
            columns: ["display_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "device_heartbeats_display_id_shop_id_fkey"
            columns: ["display_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "shop_id"]
          },
        ]
      }
      displays: {
        Row: {
          app_version: string | null
          camera_ok: boolean | null
          created_at: string
          hardware_info: Json
          id: string
          last_heartbeat_at: string | null
          name: string
          organization_id: string
          screen_height: number | null
          screen_width: number | null
          shop_id: string
          slug: string
          status: Database["public"]["Enums"]["device_status"]
          updated_at: string
        }
        Insert: {
          app_version?: string | null
          camera_ok?: boolean | null
          created_at?: string
          hardware_info?: Json
          id?: string
          last_heartbeat_at?: string | null
          name: string
          organization_id: string
          screen_height?: number | null
          screen_width?: number | null
          shop_id: string
          slug: string
          status?: Database["public"]["Enums"]["device_status"]
          updated_at?: string
        }
        Update: {
          app_version?: string | null
          camera_ok?: boolean | null
          created_at?: string
          hardware_info?: Json
          id?: string
          last_heartbeat_at?: string | null
          name?: string
          organization_id?: string
          screen_height?: number | null
          screen_width?: number | null
          shop_id?: string
          slug?: string
          status?: Database["public"]["Enums"]["device_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "displays_shop_id_organization_id_fkey"
            columns: ["shop_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      garment_assets: {
        Row: {
          byte_size: number | null
          content_hash: string
          created_at: string
          garment_id: string
          height: number | null
          id: string
          kind: Database["public"]["Enums"]["garment_asset_kind"]
          metadata: Json
          mime_type: string | null
          organization_id: string
          storage_bucket: string
          storage_path: string
          variant_id: string | null
          version: number
          width: number | null
        }
        Insert: {
          byte_size?: number | null
          content_hash: string
          created_at?: string
          garment_id: string
          height?: number | null
          id?: string
          kind: Database["public"]["Enums"]["garment_asset_kind"]
          metadata?: Json
          mime_type?: string | null
          organization_id: string
          storage_bucket?: string
          storage_path: string
          variant_id?: string | null
          version?: number
          width?: number | null
        }
        Update: {
          byte_size?: number | null
          content_hash?: string
          created_at?: string
          garment_id?: string
          height?: number | null
          id?: string
          kind?: Database["public"]["Enums"]["garment_asset_kind"]
          metadata?: Json
          mime_type?: string | null
          organization_id?: string
          storage_bucket?: string
          storage_path?: string
          variant_id?: string | null
          version?: number
          width?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "garment_assets_garment_id_organization_id_fkey"
            columns: ["garment_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "garments"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "garment_assets_variant_id_garment_id_fkey"
            columns: ["variant_id", "garment_id"]
            isOneToOne: false
            referencedRelation: "garment_variants"
            referencedColumns: ["id", "garment_id"]
          },
        ]
      }
      garment_variants: {
        Row: {
          color_hex: string
          color_name: string
          created_at: string
          garment_id: string
          id: string
          is_active: boolean
          organization_id: string
          shop_id: string
          sku: string | null
          updated_at: string
        }
        Insert: {
          color_hex: string
          color_name: string
          created_at?: string
          garment_id: string
          id?: string
          is_active?: boolean
          organization_id: string
          shop_id: string
          sku?: string | null
          updated_at?: string
        }
        Update: {
          color_hex?: string
          color_name?: string
          created_at?: string
          garment_id?: string
          id?: string
          is_active?: boolean
          organization_id?: string
          shop_id?: string
          sku?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "garment_variants_garment_id_organization_id_fkey"
            columns: ["garment_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "garments"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "garment_variants_garment_id_shop_id_fkey"
            columns: ["garment_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "garments"
            referencedColumns: ["id", "shop_id"]
          },
        ]
      }
      garments: {
        Row: {
          brand: string | null
          category: string
          created_at: string
          currency_code: string | null
          description: string | null
          id: string
          is_active: boolean
          name: string
          organization_id: string
          price_minor: number | null
          shop_id: string
          sku: string
          updated_at: string
        }
        Insert: {
          brand?: string | null
          category: string
          created_at?: string
          currency_code?: string | null
          description?: string | null
          id?: string
          is_active?: boolean
          name: string
          organization_id: string
          price_minor?: number | null
          shop_id: string
          sku: string
          updated_at?: string
        }
        Update: {
          brand?: string | null
          category?: string
          created_at?: string
          currency_code?: string | null
          description?: string | null
          id?: string
          is_active?: boolean
          name?: string
          organization_id?: string
          price_minor?: number | null
          shop_id?: string
          sku?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "garments_shop_id_organization_id_fkey"
            columns: ["shop_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      installations: {
        Row: {
          created_at: string
          display_id: string
          id: string
          installed_on: string | null
          notes: string | null
          organization_id: string
          shop_id: string
          software_version: string | null
          status: Database["public"]["Enums"]["installation_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_id: string
          id?: string
          installed_on?: string | null
          notes?: string | null
          organization_id: string
          shop_id: string
          software_version?: string | null
          status?: Database["public"]["Enums"]["installation_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_id?: string
          id?: string
          installed_on?: string | null
          notes?: string | null
          organization_id?: string
          shop_id?: string
          software_version?: string | null
          status?: Database["public"]["Enums"]["installation_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "installations_display_id_organization_id_fkey"
            columns: ["display_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "installations_display_id_shop_id_fkey"
            columns: ["display_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "shop_id"]
          },
          {
            foreignKeyName: "installations_shop_id_organization_id_fkey"
            columns: ["shop_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          id: string
          name: string
          slug: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          slug: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          slug?: string
          updated_at?: string
        }
        Relationships: []
      }
      recommendation_events: {
        Row: {
          category: string | null
          created_at: string
          id: string
          latency_ms: number | null
          model_version: string
          organization_id: string
          request_id: string
          results: Json
          seed_variant_ids: string[]
          session_id: string
          shop_id: string
        }
        Insert: {
          category?: string | null
          created_at?: string
          id?: string
          latency_ms?: number | null
          model_version: string
          organization_id: string
          request_id: string
          results?: Json
          seed_variant_ids?: string[]
          session_id: string
          shop_id: string
        }
        Update: {
          category?: string | null
          created_at?: string
          id?: string
          latency_ms?: number | null
          model_version?: string
          organization_id?: string
          request_id?: string
          results?: Json
          seed_variant_ids?: string[]
          session_id?: string
          shop_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "recommendation_events_session_id_organization_id_fkey"
            columns: ["session_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "recommendation_events_session_id_shop_id_fkey"
            columns: ["session_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "shop_id"]
          },
        ]
      }
      session_events: {
        Row: {
          actor_kind: Database["public"]["Enums"]["actor_kind"]
          created_at: string
          id: string
          message_id: string
          occurred_at: string
          organization_id: string
          payload: Json
          protocol_version: number
          session_id: string
          shop_id: string
          type: string
        }
        Insert: {
          actor_kind: Database["public"]["Enums"]["actor_kind"]
          created_at?: string
          id?: string
          message_id: string
          occurred_at: string
          organization_id: string
          payload?: Json
          protocol_version: number
          session_id: string
          shop_id: string
          type: string
        }
        Update: {
          actor_kind?: Database["public"]["Enums"]["actor_kind"]
          created_at?: string
          id?: string
          message_id?: string
          occurred_at?: string
          organization_id?: string
          payload?: Json
          protocol_version?: number
          session_id?: string
          shop_id?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "session_events_session_id_organization_id_fkey"
            columns: ["session_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "session_events_session_id_shop_id_fkey"
            columns: ["session_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "shop_id"]
          },
        ]
      }
      sessions: {
        Row: {
          created_at: string
          display_id: string
          end_reason: Database["public"]["Enums"]["session_end_reason"] | null
          ended_at: string | null
          id: string
          last_activity_at: string
          locale: string
          organization_id: string
          pairing_claimed_at: string | null
          pairing_expires_at: string
          pairing_revoked_at: string | null
          pairing_token_hash: string
          shop_id: string
          started_at: string | null
          status: Database["public"]["Enums"]["session_status"]
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_id: string
          end_reason?: Database["public"]["Enums"]["session_end_reason"] | null
          ended_at?: string | null
          id?: string
          last_activity_at?: string
          locale?: string
          organization_id: string
          pairing_claimed_at?: string | null
          pairing_expires_at: string
          pairing_revoked_at?: string | null
          pairing_token_hash: string
          shop_id: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["session_status"]
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_id?: string
          end_reason?: Database["public"]["Enums"]["session_end_reason"] | null
          ended_at?: string | null
          id?: string
          last_activity_at?: string
          locale?: string
          organization_id?: string
          pairing_claimed_at?: string | null
          pairing_expires_at?: string
          pairing_revoked_at?: string | null
          pairing_token_hash?: string
          shop_id?: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["session_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "sessions_display_id_organization_id_fkey"
            columns: ["display_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "sessions_display_id_shop_id_fkey"
            columns: ["display_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "displays"
            referencedColumns: ["id", "shop_id"]
          },
          {
            foreignKeyName: "sessions_shop_id_organization_id_fkey"
            columns: ["shop_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      shops: {
        Row: {
          address_line: string | null
          city: string | null
          country_code: string | null
          created_at: string
          default_locale: string
          id: string
          name: string
          organization_id: string
          slug: string
          timezone: string
          updated_at: string
        }
        Insert: {
          address_line?: string | null
          city?: string | null
          country_code?: string | null
          created_at?: string
          default_locale?: string
          id?: string
          name: string
          organization_id: string
          slug: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          address_line?: string | null
          city?: string | null
          country_code?: string | null
          created_at?: string
          default_locale?: string
          id?: string
          name?: string
          organization_id?: string
          slug?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shops_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      size_charts: {
        Row: {
          created_at: string
          garment_id: string | null
          id: string
          name: string
          organization_id: string
          shop_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          garment_id?: string | null
          id?: string
          name: string
          organization_id: string
          shop_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          garment_id?: string | null
          id?: string
          name?: string
          organization_id?: string
          shop_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "size_charts_garment_id_organization_id_fkey"
            columns: ["garment_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "garments"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "size_charts_shop_id_organization_id_fkey"
            columns: ["shop_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      size_measurements: {
        Row: {
          chest_cm: number | null
          created_at: string
          hip_cm: number | null
          id: string
          inseam_cm: number | null
          length_cm: number | null
          organization_id: string
          shop_id: string
          shoulder_cm: number | null
          size_chart_id: string
          size_label: Database["public"]["Enums"]["size_label"]
          sleeve_cm: number | null
          updated_at: string
          waist_cm: number | null
        }
        Insert: {
          chest_cm?: number | null
          created_at?: string
          hip_cm?: number | null
          id?: string
          inseam_cm?: number | null
          length_cm?: number | null
          organization_id: string
          shop_id: string
          shoulder_cm?: number | null
          size_chart_id: string
          size_label: Database["public"]["Enums"]["size_label"]
          sleeve_cm?: number | null
          updated_at?: string
          waist_cm?: number | null
        }
        Update: {
          chest_cm?: number | null
          created_at?: string
          hip_cm?: number | null
          id?: string
          inseam_cm?: number | null
          length_cm?: number | null
          organization_id?: string
          shop_id?: string
          shoulder_cm?: number | null
          size_chart_id?: string
          size_label?: Database["public"]["Enums"]["size_label"]
          sleeve_cm?: number | null
          updated_at?: string
          waist_cm?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "size_measurements_size_chart_id_organization_id_fkey"
            columns: ["size_chart_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "size_charts"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "size_measurements_size_chart_id_shop_id_fkey"
            columns: ["size_chart_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "size_charts"
            referencedColumns: ["id", "shop_id"]
          },
        ]
      }
      size_recommendation_events: {
        Row: {
          accepted_size: Database["public"]["Enums"]["size_label"] | null
          alternatives: Database["public"]["Enums"]["size_label"][]
          confidence: number
          created_at: string
          garment_id: string
          id: string
          model_version: string
          organization_id: string
          rationale: string | null
          recommended_size: Database["public"]["Enums"]["size_label"]
          request_id: string
          session_id: string
          shop_id: string
          variant_id: string
        }
        Insert: {
          accepted_size?: Database["public"]["Enums"]["size_label"] | null
          alternatives?: Database["public"]["Enums"]["size_label"][]
          confidence: number
          created_at?: string
          garment_id: string
          id?: string
          model_version: string
          organization_id: string
          rationale?: string | null
          recommended_size: Database["public"]["Enums"]["size_label"]
          request_id: string
          session_id: string
          shop_id: string
          variant_id: string
        }
        Update: {
          accepted_size?: Database["public"]["Enums"]["size_label"] | null
          alternatives?: Database["public"]["Enums"]["size_label"][]
          confidence?: number
          created_at?: string
          garment_id?: string
          id?: string
          model_version?: string
          organization_id?: string
          rationale?: string | null
          recommended_size?: Database["public"]["Enums"]["size_label"]
          request_id?: string
          session_id?: string
          shop_id?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "size_recommendation_events_session_id_organization_id_fkey"
            columns: ["session_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "size_recommendation_events_session_id_shop_id_fkey"
            columns: ["session_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "shop_id"]
          },
          {
            foreignKeyName: "size_recommendation_events_variant_id_garment_id_fkey"
            columns: ["variant_id", "garment_id"]
            isOneToOne: false
            referencedRelation: "garment_variants"
            referencedColumns: ["id", "garment_id"]
          },
        ]
      }
      staff_users: {
        Row: {
          auth_user_id: string
          created_at: string
          email: string
          full_name: string | null
          id: string
          is_active: boolean
          organization_id: string
          role: Database["public"]["Enums"]["staff_role"]
          shop_id: string | null
          updated_at: string
        }
        Insert: {
          auth_user_id: string
          created_at?: string
          email: string
          full_name?: string | null
          id?: string
          is_active?: boolean
          organization_id: string
          role: Database["public"]["Enums"]["staff_role"]
          shop_id?: string | null
          updated_at?: string
        }
        Update: {
          auth_user_id?: string
          created_at?: string
          email?: string
          full_name?: string | null
          id?: string
          is_active?: boolean
          organization_id?: string
          role?: Database["public"]["Enums"]["staff_role"]
          shop_id?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "staff_users_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "staff_users_shop_id_organization_id_fkey"
            columns: ["shop_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "shops"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      tryon_jobs: {
        Row: {
          consent_id: string
          created_at: string
          error_code: string | null
          finished_at: string | null
          garment_id: string
          id: string
          input_expires_at: string | null
          input_path: string | null
          organization_id: string
          output_path: string | null
          queued_at: string
          session_id: string
          shop_id: string
          started_at: string | null
          status: Database["public"]["Enums"]["tryon_job_status"]
          updated_at: string
          variant_id: string
        }
        Insert: {
          consent_id: string
          created_at?: string
          error_code?: string | null
          finished_at?: string | null
          garment_id: string
          id?: string
          input_expires_at?: string | null
          input_path?: string | null
          organization_id: string
          output_path?: string | null
          queued_at?: string
          session_id: string
          shop_id: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["tryon_job_status"]
          updated_at?: string
          variant_id: string
        }
        Update: {
          consent_id?: string
          created_at?: string
          error_code?: string | null
          finished_at?: string | null
          garment_id?: string
          id?: string
          input_expires_at?: string | null
          input_path?: string | null
          organization_id?: string
          output_path?: string | null
          queued_at?: string
          session_id?: string
          shop_id?: string
          started_at?: string | null
          status?: Database["public"]["Enums"]["tryon_job_status"]
          updated_at?: string
          variant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tryon_jobs_consent_id_session_id_fkey"
            columns: ["consent_id", "session_id"]
            isOneToOne: false
            referencedRelation: "consents"
            referencedColumns: ["id", "session_id"]
          },
          {
            foreignKeyName: "tryon_jobs_session_id_organization_id_fkey"
            columns: ["session_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "tryon_jobs_session_id_shop_id_fkey"
            columns: ["session_id", "shop_id"]
            isOneToOne: false
            referencedRelation: "sessions"
            referencedColumns: ["id", "shop_id"]
          },
          {
            foreignKeyName: "tryon_jobs_variant_id_garment_id_fkey"
            columns: ["variant_id", "garment_id"]
            isOneToOne: false
            referencedRelation: "garment_variants"
            referencedColumns: ["id", "garment_id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      actor_kind: "STAFF" | "DEVICE" | "CUSTOMER" | "SYSTEM"
      consent_kind: "CAMERA_PROCESSING" | "PHOTO_TRYON_UPLOAD" | "ANALYTICS"
      customer_request_status:
        | "REQUESTED"
        | "ACKNOWLEDGED"
        | "FULFILLED"
        | "CANCELLED"
      device_status: "ONLINE" | "OFFLINE" | "MAINTENANCE" | "REVOKED"
      garment_asset_kind:
        | "THUMBNAIL"
        | "MOBILE_IMAGE"
        | "FRONT_IMAGE"
        | "BACK_IMAGE"
        | "OVERLAY"
        | "ALPHA_MASK"
        | "SEGMENTATION_MASK"
        | "DEPTH_MAP"
        | "FITTING_METADATA"
        | "AI_REFERENCE"
        | "MESH"
        | "MODEL_3D"
      installation_status: "ACTIVE" | "SUSPENDED" | "MAINTENANCE" | "REVOKED"
      session_end_reason:
        | "CUSTOMER_ENDED"
        | "TIMEOUT"
        | "DISCONNECTED"
        | "STAFF_RESET"
        | "ERROR"
      session_status: "WAITING" | "PAIRED" | "ACTIVE" | "ENDED" | "EXPIRED"
      size_label: "XS" | "S" | "M" | "L" | "XL" | "XXL" | "XXXL"
      staff_role: "ORG_OWNER" | "ADMIN" | "MANAGER" | "STAFF"
      tryon_job_status:
        | "QUEUED"
        | "RUNNING"
        | "SUCCEEDED"
        | "FAILED"
        | "CANCELLED"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      actor_kind: ["STAFF", "DEVICE", "CUSTOMER", "SYSTEM"],
      consent_kind: ["CAMERA_PROCESSING", "PHOTO_TRYON_UPLOAD", "ANALYTICS"],
      customer_request_status: [
        "REQUESTED",
        "ACKNOWLEDGED",
        "FULFILLED",
        "CANCELLED",
      ],
      device_status: ["ONLINE", "OFFLINE", "MAINTENANCE", "REVOKED"],
      garment_asset_kind: [
        "THUMBNAIL",
        "MOBILE_IMAGE",
        "FRONT_IMAGE",
        "BACK_IMAGE",
        "OVERLAY",
        "ALPHA_MASK",
        "SEGMENTATION_MASK",
        "DEPTH_MAP",
        "FITTING_METADATA",
        "AI_REFERENCE",
        "MESH",
        "MODEL_3D",
      ],
      installation_status: ["ACTIVE", "SUSPENDED", "MAINTENANCE", "REVOKED"],
      session_end_reason: [
        "CUSTOMER_ENDED",
        "TIMEOUT",
        "DISCONNECTED",
        "STAFF_RESET",
        "ERROR",
      ],
      session_status: ["WAITING", "PAIRED", "ACTIVE", "ENDED", "EXPIRED"],
      size_label: ["XS", "S", "M", "L", "XL", "XXL", "XXXL"],
      staff_role: ["ORG_OWNER", "ADMIN", "MANAGER", "STAFF"],
      tryon_job_status: [
        "QUEUED",
        "RUNNING",
        "SUCCEEDED",
        "FAILED",
        "CANCELLED",
      ],
    },
  },
} as const
